package io.openfuture.api.exception

class FunctionCallException(message: String?) : RuntimeException(message)